### ISSUE TITLE
use subcommand in ctl tool

### ISSUE THREAD

**Issue by xiang90** [c-fs/cfs#14]

**Comment by xiang90** [comment]
@yutongp Do you have any interest in this one?

I want to use something like https://github.com/spf13/cobra

**Comment by yutongp** [comment]
sure. I will look at this.

**Comment by yutongp** [comment]
closed at https://github.com/c-fs/cfs/pull/43

**Comment by xiang90** [comment]
@yutongp Thanks for your effort!
