### ISSUE TITLE
create a client lib

### ISSUE THREAD

**Issue by xiang90** [c-fs/cfs#15]
should be a very thin wrapper around grpc client

**Comment by yutongp** [comment]
I can work on this one. What do you expect? A `client` struct hold multiply end addresses or one `client` connect to one node?

**Comment by xiang90** [comment]
@yutongp cfsctl should be a consumer of cfsclient. it should not use the grpc client directly. so cfsclient is just a thin wrapper around grpc client. it provides better ux.

**Comment by yichengq** [comment]
Have been implemented in https://github.com/c-fs/cfs/blob/master/client/client.go
