### ISSUE TITLE
explore logging framework

### ISSUE THREAD

**Issue by xiang90** [c-fs/cfs#23]

**Comment by wangtuanjie** [comment]
Is it sure use http://github.com/c-fs/clog ?

**Comment by xiang90** [comment]
@wangtuanjie Another option is https://github.com/Sirupsen/logrus. 

But I prefer clog. What do you think?

**Comment by wangtuanjie** [comment]
1. logrus看了下文档，功能太多了。
2. clog有试用，侵入太多，对std.flag包的侵入和写文件的隐喻。

**Comment by wangtuanjie** [comment]
期望的日志模块

**Comment by wangtuanjie** [comment]
对日志模块的期望

**Comment by wangtuanjie** [comment]
我们简化下clog或者https://github.com/qiniu/log, 你怎么看？

**Comment by xiang90** [comment]
How about https://github.com/coreos/pkg/tree/master/capnslog? 

qiniu/log is also fine. I would like to use something as simple as possible.

**Comment by wangtuanjie** [comment]
capnslog don't have default logger, must define log := capnslog.NewPackageLogger(...) before use it.

**Comment by xiang90** [comment]
@wangtuanjie That is fine in my opinion. But you can use the qiniu one (which is quite simple). do you know if there is anyone actively maintaining that log pkg? Does qiniu use it in production?

**Comment by wangtuanjie** [comment]
@xiang90  Does qiniu use it in production?
yes, it is a common util at qiniu which generate 10 billion logs per day.

**Comment by xiang90** [comment]
@wangtuanjie OK. Let us try qiniu/log.
