### ISSUE TITLE
readBlock function logic

### ISSUE THREAD

**Issue by wangtuanjie** [c-fs/cfs#52]
readBlock(rs io.ReadSeeker, p []byte, index, bs int64), should return err when len(p) < the block size ?

**Comment by yunxing** [comment]
An eof should be returned. Is there a testcase to reproduce the issue you
are talking about ?

**Comment by xiang90** [comment]
@wangtuanjie @yunxing 

Hm... If len(p) < block_size, I think we should not return an error. It is just like reading a file with a small required length.

**Comment by wangtuanjie** [comment]
@yunxing test case

``` go
func TestReadBlock(t *testing.T) {

    var (
        blkSize = int64(20)
        writen  = blkSize - crc32Len
        blkIdx  = int64(0)
    )

    f := setUpBlockTestFile(blkSize, t)

    p := make([]byte, writen)
    for i := int64(0); i < 10; i++ {
        p[i] = 'X'
    }
    if err := writeBlock(f, blkIdx, blkSize, p); err != nil {
        t.Fatal(err)
    }

    rb := make([]byte, 1)
    _, err := readBlock(f, rb, blkIdx, blkSize)
    t.Fatal("readBlock:", err)
}
```

now test output

```
--- FAIL: TestReadBlock (0.00s)
    block_test.go:254: readBlock: disk: not a valid CRC
```

**Comment by wangtuanjie** [comment]
@xiang90 I agree with you

**Comment by yutongp** [comment]
Reading 1 byte now returns error because it less than CRC length.

I don't think readBlock less than block size should return error as well.
But may be return error when Len < crcSize

**Comment by wangtuanjie** [comment]
Not relevant to CRC length.
readBlock(f, make([]byte, crc32Len+1), blkIdx, blkSize) return ErrBadCRC also.

**Comment by yunxing** [comment]
I see what you mean, it is definitely a bug. Will fix it.

**Comment by yutongp** [comment]
I think we can enforce `len(p) == blockSize`, otherwise we can hardly calculate the last partly block crc, since we don't know the real size of last partly block.

Another option is we allow read length < blockSize for full block.
