### ISSUE TITLE
cgo warning msg when run go test under erasure directory

### ISSUE THREAD

**Issue by yutongp** [c-fs/cfs#59]
run `go test` under `/erasure`

```
# github.com/c-fs/cfs/erasure
./erasure.go:45:31: warning: unknown attribute '__gcc_struct__' ignored [-Wattributes]
        } __attribute__((__packed__, __gcc_struct__)) *a = v;
                                     ^
./erasure.go:65:31: warning: unknown attribute '__gcc_struct__' ignored [-Wattributes]
        } __attribute__((__packed__, __gcc_struct__)) *a = v;
                                     ^
./erasure.go:79:31: warning: unknown attribute '__gcc_struct__' ignored [-Wattributes]
        } __attribute__((__packed__, __gcc_struct__)) *a = v;
                                     ^
./erasure.go:100:31: warning: unknown attribute '__gcc_struct__' ignored [-Wattributes]
        } __attribute__((__packed__, __gcc_struct__)) *a = v;
                                     ^
./erasure.go:117:31: warning: unknown attribute '__gcc_struct__' ignored [-Wattributes]
        } __attribute__((__packed__, __gcc_struct__)) *a = v;
                                     ^
5 warnings generated.
# github.com/c-fs/cfs/erasure
clang: warning: argument unused during compilation: '-pthread'
# github.com/c-fs/cfs/erasure
clang: warning: argument unused during compilation: '-pthread'
```

@yunxing could you take a look?
And close this issue if we don't need to worry about it.

on Mac with:

```
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

**Comment by yutongp** [comment]
seems by running command `CC=clang go test` resolve all warnings.

**Comment by xiang90** [comment]
ok. seems like a documentation issue (we should suggest people to use clang on mac). we need to test gcc on linux though.

**Comment by 5kg** [comment]
I guess you accidentally override the CC environment variable. go toolchain takes care when compiling with `clang` to not generating these warnings (see [1](https://github.com/golang/go/blob/cf932cd897a3eaf3aa6fec3ba5d0ab1d9107eebb/src/cmd/go/build.go#L2689),[2](https://github.com/golang/go/blob/e8fc93ea45ca0147f24f61f5ed48e68b57d473df/src/cmd/cgo/out.go#L652)).

And by default, `go` will use `clang` on Mac (at least for OSX >= 10.8) unless you set the CC environment variable (see [3](https://github.com/golang/go/blob/67805eaa950c5318bfe02943cc175da6729919a9/src/cmd/dist/util.go#L454), [4](https://github.com/golang/go/blob/cf932cd897a3eaf3aa6fec3ba5d0ab1d9107eebb/src/cmd/dist/build.go#L164)).

**Comment by yutongp** [comment]
My CC/GCC/CXX/CPP env are all empty...

**Comment by yutongp** [comment]
@5kg  you are right. I just found out my `go env` messed up.

```
$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fno-common"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by yunxing** [comment]
@5kg: Good catch. 

Any ideas why it is messed up with gcc?

I think we should fix that, or at least find out the reason that causes it.
