### ISSUE TITLE
disk.ReadAt not return EOF

### ISSUE THREAD

**Issue by wangtuanjie** [c-fs/cfs#77]
``` go
disk.WriteAt("cfs0/newfile", []byte("123"), 0)

buf := make([]byte, 3)
disk.ReadAt("cfs0/newfile", buf, 0)  return 3, nil
disk.ReadAt("cfs0/newfile", buf, 3)  return 0, nil   // actual expected 0, io.EOF?
```

When disk.Readat  wrap to io.Reader interface, then as a read param for io.Copy, it will dead loop.

**Comment by yunxing** [comment]
Do we actually want to return eof when you just read enough bytes into your buffer?

**Comment by yunxing** [comment]
sorry I misread that. You are right, this is a bug if you readat 3 and return nil error.
