### ISSUE TITLE
Remove int32 support 

### ISSUE THREAD

**Issue by yunxing** [c-fs/cfs#84]
I don't think any modern servers are using int32 anymore. I propose we change all int64 types to int so that we don't need explicit type conversions.

**Comment by yunxing** [comment]
@xiang90

**Comment by xiang90** [comment]
sure

**Comment by wangtuanjie** [comment]
Proto not support int. https://developers.google.com/protocol-buffers/docs/proto3#scalar

**Comment by yunxing** [comment]
Good point. We can either use int64 for APIs or change everything explicitly to int64.
